### ISSUE TITLE
Improve gantt vision

### ISSUE THREAD

**Issue by domingoruiz** [a-aznar/canvas-assignments-timeline-extension#3]
Hello good. I think it would be a pretty good improvement if the gantt occupied the width of the entire screen to be able to have a better view, since today it is quite narrow and allows very few days to be seen simultaneously. 

Thank you and congratulations for the tool.

**Comment by a-aznar** [comment]
Hi @domingoruiz thanks for the comment!

Could you please add a screenshot to better understand the width problem? From what I could test, it does fit the whole width for me, except the very right side that has a right panel with a "To Do" list.

I'm not sure I fully understand the issue. Have you tried scrolling? It should zoom in/out and let you see up to several months in the timeline.

**Comment by a-aznar** [comment]
What's your resolution? How many days do you want to see simultaneously?

If you scroll it zooms out and let's you see 2+ months:

![image](https://github.com/a-aznar/canvas-assignments-timeline-extension/assets/18106097/d271142a-fc4a-499e-b512-8b8b35bb5492)

**Comment by domingoruiz** [comment]
My proposal from the beginning is that the Gantt chart could be placed as I propose in the screenshot so that it occupies the entire width of the screen and the information can be seen much better by moving the to do list down.

Thanks you.

![Propuesta](https://github.com/a-aznar/canvas-assignments-timeline-extension/assets/13834425/27331181-c856-4dab-8bb9-45f793509cb0)

**Comment by domingoruiz** [comment]
It's possible?

**Comment by a-aznar** [comment]
I believe it should be possible yes. Maybe with a side button to expand/collapse?

Feel free to open a PR for it 🙂

**Comment by domingoruiz** [comment]
Now I don't have for developing it, but I think that it's very necessary to see well all the activities.

Thanks you.

**Comment by domingoruiz** [comment]
In the pull request #7 I present my own solution for the proposal I made.

**Comment by domingoruiz** [comment]
It's true that it looks different on my computer than yours. I suppose it has to do with my university's website (UOC) since I have tried it on several devices. I'm going to keep my fork open for personal use. Anyway thank you very much.
