### ISSUE TITLE
Eliminar del timeline asignaturas terminadas

### ISSUE THREAD

**Issue by DanielOSeg** [a-aznar/canvas-assignments-timeline-extension#5]
Hola. 

Lo primero de todo, gracias por la extension. ¡¡Me vino estupendamente el semestre pasado!!

Desgraciadamente, en este semestre veo que me salen las asignaturas de este semestre (menos 1) y las del anterior y me preguntaba si podrías arreglarlo.

Entiendo si no quieres o no puedes, pero tenía que intentarlo.

Gracias, en cualquier caso. 

¡¡Un saludo!!

![image](https://github.com/a-aznar/canvas-assignments-timeline-extension/assets/93029295/0c05a65f-c81c-4e9f-9dd8-9fd5c5575935)

**Comment by a-aznar** [comment]
It was already fixed, please update the extension 🙂

**Comment by DanielOSeg** [comment]
Hi. Thanks for your quick reply.

I might been doing something wrong, but after the updating, it appears the same in the dashboard. 

I tried both Edge and Chrome, the same result.

Sorry again for the inconvenience caused and thanks.

**Comment by a-aznar** [comment]
I believe reinstalling should fix it.

It seems like there was a missing upgrade for the manifest version which prevents the automatic update. I have now fixed it but will take a while to take effect on the extensions store. The changes are in the last version available already though, so reinstalling the extension should fix it.

**Comment by DanielOSeg** [comment]
Solved! Thanks!!
